# Generated by Django 3.1.2 on 2020-11-06 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=20)),
                ('examid', models.IntegerField()),
                ('answer', models.TextField(max_length=200)),
                ('currenttime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('examName', models.CharField(max_length=200)),
                ('branchCode', models.CharField(max_length=10)),
                ('subjectCode', models.CharField(max_length=10)),
                ('time', models.IntegerField(default='36')),
                ('startExam', models.DateTimeField()),
                ('endExam', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=500)),
                ('option1', models.TextField(max_length=200)),
                ('option2', models.TextField(max_length=200)),
                ('option3', models.TextField(max_length=200)),
                ('option4', models.TextField(max_length=200)),
                ('correctAns', models.TextField(max_length=200)),
                ('examId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.examtable')),
            ],
        ),
    ]
