# Generated by Django 3.1.2 on 2020-11-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=20)),
                ('examid', models.IntegerField()),
                ('totalmark', models.IntegerField()),
                ('getmark', models.IntegerField()),
                ('totalquestion', models.IntegerField()),
                ('questionattempt', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('currenttime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='answertable',
            name='questionid',
            field=models.IntegerField(default=0),
        ),
    ]
