# Generated by Django 3.1.2 on 2020-11-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0003_auto_20201107_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='answertable',
            name='answer',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='examtable',
            name='time',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='questiontable',
            name='correctAns',
            field=models.IntegerField(default='0'),
        ),
    ]
