# Generated by Django 3.1.2 on 2020-11-07 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0004_auto_20201107_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OptionTable',
        ),
        migrations.AlterField(
            model_name='questiontable',
            name='correctAns',
            field=models.IntegerField(default='0', validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
    ]
